# Generated by Django 2.2.2 on 2019-06-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/img/icons/person.png', upload_to='user/%Y/%m/%d'),
        ),
    ]
